run:
  tests: true
  build-tags:
    - bench
    - !bench
  
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gci:
    sections:
      - standard 
      - default
      - prefix(github.com/AnnDutova/otus_go_hw)
    skip-generated: false
  
  depguard:
    rules:
      tests:
        files:
          - $test
        allow:
          - $gostd
          - github.com/AnnDutova/otus_go_hw
          - github.com/stretchr/testify